import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/sonner";
import fimage from "../../../../public/pics/HomeScreen.webp"
import Image from "next/image";
import Link from "next/link";
import { Nav } from "@/components/myComp/nav";
import { DramaContextProvider } from "@/context/dramaContext"
import { NavAndBtn } from "@/components/myComp/NavAndBtn";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <DramaContextProvider>
        <AuthProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <div className="m-12">
              <Image
                className="dark:invert mt-4"
                src={fimage}
                alt="Next.js logo"

                priority
              />
              <NavAndBtn/>

            </div>
            {children}
            <Toaster />
          </body>
        </AuthProvider>
      </DramaContextProvider>
    </html>
  );
}
