import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/sonner";
import Image from "next/image";
import fimage from "../../public/pics/HomeScreen.webp"
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <div className="m-12">
        <Image
          className="dark:invert mt-4"
          src={fimage}
          alt="Next.js logo"
          
          priority
        />
       <div className="bg-black w-full h-12 m-2 flex">
        <Link href="/Home" className="text-white">
          Home
        </Link>
       </div>
       
    </div>
        {children}
        <Toaster />
      </body>
      </AuthProvider>
    </html>
  );
}
